---
# Ansible playbook for an AWX server.
#
# @author Jeff Geerling (2017).

- hosts: awx
  gather_facts: yes
  become: yes

  vars:
    awx_version: "devel"
    postgres_data_dir: "/root/pgdocker"
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - { role: geerlingguy.awx, postgres_data_dir: '/root/pgdocker' }
